#!/usr/bin/env python3
"""Generate C constants for one solution of the catalog.

    python3 gen_constants.py contracts.jsonl <solution id> > constants.h

The catalog is the source of truth; kernels must not hand-write weights, coefficients or block
scales. Standard library only.
"""
import json, sys


def arr(ctype, name, values, fmt=str):
    return 'static constexpr %s %s[%d] = {%s};' % (ctype, name, len(values), ', '.join(fmt(v) for v in values))


def emit(rec):
    fam = rec['family']
    out = ['// Generated by gen_constants.py from the solutions catalog. Do not edit by hand.',
           '// solution: %s  (schema %s, family %s)' % (rec['id'], rec['schema'], fam),
           '#pragma once']

    if fam == 'five_plane_encoding':
        lam = rec['reconstruction_coefficients']
        out.append(arr('int', 'kWeights', rec['weights']))
        out.append('static constexpr int kPlanes = %d;' % rec['products'])
        out.append(arr('int', 'kReconstruction', lam))
        out.append(arr('int', 'kScaleA', rec['block_scales']['A']))
        out.append(arr('int', 'kScaleB', rec['block_scales']['B']))
        out.append('// planes: %s' % rec['faces'])
        return '\n'.join(out) + '\n'

    if fam not in ('direct_limb_products', 'width_catalog'):
        raise SystemExit('no constant form for family ' + fam)

    wa, wb = rec['weights_A'], rec['weights_B']
    out.append('static constexpr int kLimbsA = %d, kLimbsB = %d, kProducts = %d;' % (len(wa), len(wb), rec['products']))
    out.append(arr('int', 'kWeightsA', wa))
    out.append(arr('int', 'kWeightsB', wb))
    out.append(arr('int', 'kGroupCoefficient', rec['group_output_coefficients']))
    out.append(arr('long long', 'kBoundPerElement', rec['bound_per_element']))
    out.append(arr('long long', 'kSafeK', rec['safe_k_fp32_accumulator']))
    sa = rec['block_scale_assignment']

    if fam == 'direct_limb_products':
        groups = rec['limb_pairs']
        if groups and isinstance(groups[0][0], int):
            groups = [groups]
        coef = rec['group_output_coefficients']
        pairs = [p for g in groups for p in g]
        group_of = [gi for gi, g in enumerate(groups) for _ in g]
        out.append('// C = sum over groups g of kGroupCoefficient[g] * D_g;')
        out.append('// D_g accumulates the products of group g, each scaled by kPairCoefficient')
        out.append('static constexpr int kGroups = %d;' % len(groups))
        out.append('static constexpr int kLimbPairs[%d][2] = {%s};'
                   % (len(pairs), ', '.join('{%d, %d}' % (p[0], p[1]) for p in pairs)))
        out.append(arr('int', 'kProductGroup', group_of))
        scale = []
        for (i, j), g in zip(pairs, group_of):
            num = wa[i] * wb[j]
            if num % coef[g]:
                raise SystemExit('pair coefficient %d is not a multiple of the group coefficient %d' % (num, coef[g]))
            scale.append(num // coef[g])
        out.append(arr('int', 'kPairCoefficient', scale))
        if 'pairs' in sa:
            out.append('// E4M3 block scales per product, A side and B side; %s' % sa.get('rule', ''))
            out.append('static constexpr int kBlockScales[%d][2] = {%s};'
                       % (len(sa['pairs']), ', '.join('{%s, %s}' % (p[0], p[1]) for p in sa['pairs'])))
    else:
        out.append('// products are planes: linear combinations of limbs, indexed 0..%d' % (rec['products'] - 1))
        out.append(arr('int', 'kPlaneIndex', rec['limb_pairs']))
        out.append('// %s' % sa.get('rule', ''))
        out.append('// block scale format: %s, packed divisor per side: %s'
                   % (sa.get('format'), sa.get('packed_divisor_each_side')))
        out.append(arr('int', 'kScaleA', sa['A']))
        out.append(arr('int', 'kScaleB', sa['B']))
        out.append('// sign carried by: %s' % ', '.join(sa['sign_side']))
        if 'times3' in sa:
            out.append(arr('int', 'kTimes3A', sa['times3']['A']))
            out.append(arr('int', 'kTimes3B', sa['times3']['B']))
    return '\n'.join(out) + '\n'


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    with open(sys.argv[1], encoding='utf-8') as f:
        recs = {r['id']: r for r in (json.loads(l) for l in f if l.strip()) if r.get('kind') == 'solution'}
    if sys.argv[2] not in recs:
        raise SystemExit('unknown solution id; known: ' + ', '.join(sorted(recs)))
    sys.stdout.write(emit(recs[sys.argv[2]]))


if __name__ == '__main__':
    main()
